#!/usr/bin/env node
/**
 * inline-css — compiles app/globals.css (Tailwind v4) into plain CSS and writes it
 * as a string constant (lib/critical-css.ts), so layout.tsx can inline it directly
 * into the HTML via a <style> tag instead of a separate linked stylesheet.
 *
 * Why: some corporate proxies / security extensions strip or block separate CSS
 * (text/css) requests to brand-new/unclassified domains while letting the base HTML
 * document through. Inlining removes that dependency entirely — the styles arrive
 * as part of the page itself, not a resource that can be blocked independently.
 *
 * Runs automatically before every build via the "prebuild" npm script.
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import postcss from "postcss";
import tailwindcss from "@tailwindcss/postcss";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const input = join(root, "app/globals.css");
const output = join(root, "lib/critical-css.ts");

const css = await readFile(input, "utf8");
const result = await postcss([tailwindcss({ base: root })]).process(css, {
  from: input,
});

await mkdir(dirname(output), { recursive: true });
await writeFile(
  output,
  `// AUTO-GENERATED by scripts/inline-css.mjs — do not edit by hand. Runs on every build.\nexport const criticalCss = ${JSON.stringify(result.css)};\n`
);

console.log(`✓ Inlined CSS: ${(result.css.length / 1024).toFixed(1)} KB → lib/critical-css.ts`);
